### ISSUE TITLE
Package scheduler is missing in bundle

### ISSUE THREAD

**Issue by yekver** [dai-shi/use-context-selector#34]
Seems that `scheduler` packages should be not used as a peerDependency, coz this can affect other packages
```
Module not found: Error: Can't resolve 'scheduler' in '...\projectName\node_modules\formik\node_modules\use-context-selector\dist'
```

**Comment by dai-shi** [comment]
https://github.com/formium/formik/pull/2846/files#diff-bb9bd4f1dbd843424d2c07aab952490a2b9c95c6d2474db9a0ee03eed56cfaf1R43

Okay, so formik v3 is trying to use use-context-selector.
They need to add `scheduler` in their peer dependencies.

We have some discussions about peer dependencies in [jotai](https://github.com/pmndrs/jotai) repo.
It's really annoying and only the solution seems app developers to install peer dependencies explicitly. Note npm7 does it by default.

I don't think adding it in dependencies is not an option, because it might lead having two versions of `scheduler` which doesn't work at all (like `react`).

**Comment by dai-shi** [comment]
Thanks @yekver for reporting the issue.

Pinning @jaredpalmer. Also notice there is the latest version, which is better (without hacks) in a long term.
