### ISSUE TITLE
Errors got when I use context.provider

### ISSUE THREAD

**Issue by Yulight1401** [dai-shi/use-context-selector#37]
Hello, when I try the example code in my project, I got these errors, and page go blank. I have search this problem but cannot find solution.

```
"react": "^16.8.6",
"use-context-selector": "^1.3.5",
"scheduler": "^0.20.1",
```

![image](https://user-images.githubusercontent.com/11702176/104431206-96fb4c80-55c2-11eb-9be0-e4531093ed1b.png)

**Comment by dai-shi** [comment]
Hm, not sure what is existingProxy.
Could you create a minimal repro with codesandbox?

**Comment by prakash1998** [comment]
Hi, i got the similar error and found that it is because of react-hot-loader in my case, so i had removed hot on temporary basis from my app, so it don't preserve state on hot reload, but i think react-hot-loader may require some functions to restore/preserve states, this library may miss it, it's my assumption, i'll edit comment after a bit of research on exact cause.

**Comment by dai-shi** [comment]
react-hot-loader is being deprecated by fast refresh. If this issue only happens with react-hot-loader, it's not much worth putting effort. curious what's conflicting though. cc @theKashey

**Comment by theKashey** [comment]
Sounds like this line - https://github.com/gaearon/react-hot-loader/blob/6032f4255e0268bb794c1e9b8ae5b436400ffbb5/src/reconciler/resolver.js#L38

The question is what `existingProxy` and what is `existingProxy.getCurrent`. Have no idea of the error source.
