### ISSUE TITLE
What is the "stale props" issue?

### ISSUE THREAD

**Issue by ntucker** [dai-shi/use-context-selector#4]
This is mentioned in the readme.

Also, just to confirm this library is compatible with concurrent mode, right?

**Comment by dai-shi** [comment]
> stale props

Check out the doc in react-redux which describes better.
https://react-redux.js.org/api/hooks#stale-props-and-zombie-children

Also, [the RFC](https://github.com/gnoff/rfcs/blob/context-selectors/text/0000-context-selectors.md) has some descriptions:
> In addition to the above problem, many applications let react components ‘register’ selectors or other access functions that depend on that components props. There are timing issues when these selectors are run ‘too early’ and are about to be changed when new props arrive which can lead to unexpected errors (zombie-child problem in react redux hooks) and wasted work (old selector ran but it needs to run again with new props, or this tree is going to unmount because of a parent that was updated so the selector never needed to be run in the first place)

> compatible with concurrent mode

I think so, because basically it's the same technique used in react-tracked and reactive-react-redux.

**Comment by ntucker** [comment]
Thanks for the info!
