### ISSUE TITLE
Component updates once when it shouldn't

### ISSUE THREAD

**Issue by dgpedro** [dai-shi/use-context-selector#41]
Hi there!

First let me tell you I'm not sure if this is a bug or if this behavior is intentionally.

To demonstrate my issue, I've created a simple example [here](https://codesandbox.io/s/use-context-selector-mdlv1?file=/src/App.js).

In that example, I'm `console.log` in both components just to know when they update. Every time I switch inputs and insert one char, the previous component logs in the console, but only once.

Just wanted ask if I'm doing something wrong or if it's supposed to work like that, because as I understand the component should only update when the selected context also changed, which doesn't seem to be the case there... unless I'm misunderstanding something... :/

Thanks in advance, and nice work with this package :)

**Comment by dai-shi** [comment]
Hey, thanks for jumping in.
It's a bit of [technical detail](https://github.com/dai-shi/use-context-selector#technical-memo), but it's actually the whole reason of the current version (v1.3) exists.
I'm aware of the behavior and it is intentional (not desired though, and there might be some better ways). There are some extra re-renders, but they are not committed. So, it doesn't update the DOM, and end users never see it.
This lib tries its best to support concurrent mode in userland, and it's how it works. (If react officially provides a similar hook, it should behave better.)

The rational is render functions must be pure and console.log is side effect.
To see it behaves somewhat expected, use useEffect for console.log.
https://codesandbox.io/s/use-context-selector-forked-3j9ve

**Comment by dgpedro** [comment]
Hi.
Yes, the console.log was just to explain better... Anyway, I noticed that also the component children do not re-render, so this extra re-render should not have big impact.

If behavior is intentional, I got nothing more to add :)

Thanks for the explanation.
