### ISSUE TITLE
Not able to stop the re-rendering of components

### ISSUE THREAD

**Issue by kalyanidz** [dai-shi/use-context-selector#79]
Thank you for making such an library, it was a relief for us when we were facing issues of multiple re-renders.

We went through the document and tried the counter example usafe section from [https://www.npmjs.com/package/use-context-selector](https://www.npmjs.com/package/use-context-selector)

However, when we added console.log in Counter1 and Counter2 component, both the console logs were getting printed even if we changed value of either of them.
Here is the sandbox for the same - https://codesandbox.io/s/react-use-context-selector-forked-b0z68l?file=/src/index.js

I am sure, we are missing something here. Pl let us know what should be the correct way to use it. 
Pl help @dai-shi

**Comment by dai-shi** [comment]
Hey, thanks for using the library.
This is a little technical, but it uses what I call dual-render-one-commit workaround.
If you wrap console.log with useEffect, you would see more expected result.

https://codesandbox.io/s/react-use-context-selector-forked-iy2ehu

Closing as this is intentional behavior, but feel free to add comments.

**Comment by kalyanidz** [comment]
That makes sense! Thanks a lot for clarifying this 👍🏻
